//! Known-answer test (KAT) vectors for the crypto layer.
//!
//! These freeze the exact outputs of Argon2id, HKDF-SHA256, and
//! XChaCha20-Poly1305 for fixed inputs. Every other implementation of the vault
//! (WASM, Swift/Kotlin via UniFFI) MUST reproduce them bit-for-bit; divergence
//! means the key hierarchy is incompatible. The canonical values are also
//! mirrored in `tests/vectors/crypto_vectors.json`.

use chacha20poly1305::aead::{Aead, KeyInit, Payload};
use chacha20poly1305::{XChaCha20Poly1305, XNonce};
use hkdf::Hkdf;
use sha2::Sha256;

use vault_core::crypto::kdf::{derive_master_key, KdfParams};
use vault_core::crypto::{open, SealedBlob, SecretVec};

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

const KDF_SALT: [u8; 16] = [
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
];

// Frozen expected outputs (see module docs). Generated by `print_vectors`.
const ARGON2ID_WASM_MIN_HEX: &str =
    "24edee7533ec4ecb0814c8d48e7ade898f92e52873dc02177b4dfddccc35591e";
const HKDF_HEX: &str = "a61e707dfd17ad12828f6daaf43dac41e19c884bb1e578f9b1dd08a627a9d71d";
const XAEAD_KEY_HEX: &str = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";
const XAEAD_NONCE_HEX: &str = "000102030405060708090a0b0c0d0e0f1011121314151617";
const XAEAD_AAD: &[u8] = b"vault-core-kat-aad";
const XAEAD_PLAINTEXT: &[u8] = b"the quick brown fox";
const XAEAD_CIPHERTEXT_HEX: &str =
    "eaaa6a5fe1a7e4cd586444bca425c6c82d2850901a3ccda0d4b8c36f3f4987ba33488c";

/// Run with `cargo test -p vault-core --test crypto_vectors print_vectors -- --ignored --nocapture`
/// to (re)generate the frozen constants above.
#[test]
#[ignore]
fn print_vectors() {
    let pw = SecretVec::from("vault-core test vector");
    let mk = derive_master_key(&pw, &KDF_SALT, KdfParams::WASM_MIN).unwrap();
    eprintln!("ARGON2ID_WASM_MIN_HEX = {}", hex(mk.expose()));

    let hk = Hkdf::<Sha256>::new(None, mk.expose());
    let mut okm = [0u8; 32];
    hk.expand(b"vault-core:v1:muk", &mut okm).unwrap();
    eprintln!("HKDF_HEX = {}", hex(&okm));

    let key = unhex(XAEAD_KEY_HEX);
    let nonce = unhex(XAEAD_NONCE_HEX);
    let cipher = XChaCha20Poly1305::new(key.as_slice().into());
    let ct = cipher
        .encrypt(
            XNonce::from_slice(&nonce),
            Payload {
                msg: XAEAD_PLAINTEXT,
                aad: XAEAD_AAD,
            },
        )
        .unwrap();
    eprintln!("XAEAD_CIPHERTEXT_HEX = {}", hex(&ct));
}

#[test]
fn argon2id_kat() {
    let pw = SecretVec::from("vault-core test vector");
    let mk = derive_master_key(&pw, &KDF_SALT, KdfParams::WASM_MIN).unwrap();
    assert_eq!(hex(mk.expose()), ARGON2ID_WASM_MIN_HEX);
}

#[test]
fn hkdf_kat() {
    let pw = SecretVec::from("vault-core test vector");
    let mk = derive_master_key(&pw, &KDF_SALT, KdfParams::WASM_MIN).unwrap();
    let hk = Hkdf::<Sha256>::new(None, mk.expose());
    let mut okm = [0u8; 32];
    hk.expand(b"vault-core:v1:muk", &mut okm).unwrap();
    assert_eq!(hex(&okm), HKDF_HEX);
}

#[test]
fn xchacha20poly1305_kat() {
    // `open()` must decrypt the frozen ciphertext back to the known plaintext.
    let key: [u8; 32] = unhex(XAEAD_KEY_HEX).try_into().unwrap();
    let blob = SealedBlob {
        nonce: unhex(XAEAD_NONCE_HEX),
        ciphertext: unhex(XAEAD_CIPHERTEXT_HEX),
    };
    let key = vault_core::crypto::Key256::new(key);
    let pt = open(&key, &blob, XAEAD_AAD).unwrap();
    assert_eq!(pt, XAEAD_PLAINTEXT);

    // Wrong AAD must fail authentication.
    assert!(open(&key, &blob, b"wrong-aad").is_err());
}
